FROM node:16-alpine3.12

LABEL version="1.0"
LABEL descriptio="React Frontend for the Real Estate API"

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

RUN mkdir ./node_modules/.cache && chmod -R 777 ./node_modules/.cache

CMD ["npm", "run", "start"]
