# Generated by Django 3.2.7 on 2024-04-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_photo',
            new_name='profile_photo',
        ),
    ]
